services:
  scraperr:
    image: jpyles0524/scraperr:latest
    container_name: scraperr
    command: ["npm", "run", "start"]
    environment:
      - NEXT_PUBLIC_API_URL=https://iccw0k88sc80g88w84wwwk4w.coolify.randomsynergy.xyz
      - SERVER_URL=http://scraperr_api:8000  # Keep this for internal Docker network communication
    networks:
      - web
      
  scraperr_api:
    init: true
    image: jpyles0524/scraperr_api:latest
    environment:
      - LOG_LEVEL=INFO
      - OPENAI_KEY=${OPENAI_KEY}
    container_name: scraperr_api
    volumes:
      - "$PWD/data:/project/app/data"
      - "$PWD/media:/project/app/media"
    networks:
      - web

networks:
  web:
